// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]); // getting the times
		int big = 0;
		int less = 0 ;
		double num = 0;
		for (int i = 0; i < N ; i++) // running N times 
		{
			num = Math.random();
			if (num > 0.5) // if its big we add to big otherwise we aff to less
			{
				big++;
			}
			else
			{
				less++;
			}
		}
			System.out.println("> 0.5: " + big + " times");
			System.out.println("<= 0.5: " + less + " times");
			if (!(big == 0 || less == 0)) // cheking to see no erros in printing
			{
			System.out.println("Ratio: " + (double) big / less );
			}
			

		}

	}

